# Generated by Django 5.1.5 on 2025-02-09 19:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='property',
            name='condominium',
        ),
        migrations.RemoveField(
            model_name='propertyphoto',
            name='property',
        ),
        migrations.DeleteModel(
            name='Condominium',
        ),
        migrations.DeleteModel(
            name='Property',
        ),
        migrations.DeleteModel(
            name='PropertyPhoto',
        ),
    ]
