# Generated by Django 5.1.5 on 2025-04-13 13:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
        ('public_app', '0014_alter_resetpassword_token'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='tenantuser',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='tenantuser',
            name='cpf',
            field=models.CharField(blank=True, max_length=11, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='tenantuser',
            name='function',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='tenantuser',
            name='tenant',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='public_app.client'),
        ),
    ]
