# Generated by Django 5.1.5 on 2025-04-21 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_alter_tenantuser_unique_together_tenantuser_cpf_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tenantuser',
            name='function',
            field=models.CharField(blank=True, choices=[('admin', 'Administrador'), ('recursos_humanos', 'Recursos Humanos'), ('corretor', 'Corretor de Imóveis')], max_length=255, null=True),
        ),
    ]
