# Generated by Django 5.1.5 on 2025-04-21 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0003_alter_tenantuser_function'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenantuser',
            name='telephone',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
