# Generated by Django 5.1.5 on 2025-02-04 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('public_app', '0002_client_on_trial_client_paid_until_alter_client_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='company_name',
            field=models.CharField(default='default', max_length=100, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='client',
            name='dns_name',
            field=models.CharField(default='default', max_length=20, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='client',
            name='email',
            field=models.EmailField(default='default@gmail.com', max_length=254, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='client',
            name='login_name',
            field=models.CharField(default='default', max_length=100, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='client',
            name='password',
            field=models.CharField(default='default', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='client',
            name='telephone',
            field=models.CharField(default='00000000', max_length=20),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='client',
            name='name',
            field=models.CharField(max_length=100),
        ),
    ]
