# Generated by Django 5.1.5 on 2025-02-05 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('public_app', '0006_remove_client_login_name_remove_client_password_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='client',
            name='complete_name',
        ),
        migrations.AddField(
            model_name='client',
            name='activation',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='client',
            name='on_trial',
            field=models.BooleanField(default=False),
        ),
    ]
