# Generated by Django 5.1.5 on 2025-02-22 22:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('public_app', '0010_activationcode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activationcode',
            name='code',
            field=models.IntegerField(),
        ),
    ]
