# Generated by Django 5.1.5 on 2025-02-04 21:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('public_app', '0004_rename_name_client_complete_name_client_cpf'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='cpf',
            field=models.CharField(max_length=11, unique=True),
        ),
    ]
