# Generated by Django 5.1.5 on 2025-02-05 18:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('public_app', '0008_alter_client_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='client',
            name='email',
        ),
    ]
