# Generated by Django 5.1.5 on 2025-02-25 00:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('public_app', '0011_alter_activationcode_code'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClientInventory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_count', models.IntegerField()),
                ('client_plan', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
