# Generated by Django 5.1.5 on 2025-02-04 01:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Condominium',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('code', models.IntegerField(blank=True, null=True, unique=True)),
                ('name', models.CharField(max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Property',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('code', models.IntegerField(blank=True, null=True, unique=True)),
                ('type', models.CharField(choices=[('house', 'Casa'), ('apartment', 'Apartamento'), ('farm', 'Sítio')], max_length=200)),
                ('sell_disponibility', models.BooleanField()),
                ('sell_reason_unavailability', models.CharField(blank=True, max_length=200, null=True)),
                ('rental_disponibility', models.BooleanField()),
                ('rental_reason_unavailability', models.CharField(blank=True, max_length=200)),
                ('seasonal_disponibility', models.BooleanField()),
                ('seasonal_reason_unavailability', models.CharField(blank=True, max_length=200)),
                ('zip_code', models.IntegerField(blank=True, null=True)),
                ('state', models.CharField(blank=True, max_length=100, null=True)),
                ('city', models.CharField(blank=True, max_length=100, null=True)),
                ('neighborhood', models.CharField(blank=True, max_length=100, null=True)),
                ('street', models.CharField(blank=True, max_length=200, null=True)),
                ('number', models.IntegerField(blank=True, null=True)),
                ('floor', models.IntegerField(blank=True, null=True)),
                ('condominium', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='properties', to='property.condominium')),
            ],
        ),
    ]
